### ISSUE TITLE
WDC Dataset

### ISSUE THREAD

**Issue by vicolinho** [FernandoDeMeer/GraLMatch#1]
Hello,
I have a question about the WDC dataset regarding the location. Where can I find the referenced .gz files in the code? I can not see them on the original WDC website. It would be good if you could provide a list of record identifiers and a list of pairs for training, validation, and testing.
Bests

**Comment by FernandoDeMeer** [comment]
Hello @vicolinho, just in case you couldn't find it (and for others with the same concern), we pre-process the WDC .gz files with the following script: 

https://github.com/FernandoDeMeer/GraLMatch/blob/cadafb0b2b63bb7a36e5ab1785d26a16da82699c/datainc_code/src/data/wdc/wdc_80pair_utils.py

Running this script will produce the CSV with all of the records as well as the train/val/test files with the pairs of record IDs.

**Comment by vicolinho** [comment]
Thank you @FernandoDeMeer. I found the dataset by the URL provided in your code.
